#!/bin/bash

# Activation de la coloration syntaxique et du fond noir pour vim
sed -i 's/^"syntax on/syntax on/' /etc/vim/vimrc
sed -i 's/^"set background/set background/' /etc/vim/vimrc

# Désactive "udev" sur les interfaces
rm -f /lib/udev/rules.d/75-persistent-net-generator.rules
rm -f /etc/udev/rules.d/70-persistent-net.rules

 
# Remplacement des fichiers pour bash
cp /etc/bash.bashrc /usr/share/wanparty/etc/bash.bashrc.orig
cp -f /usr/share/wanparty/etc/bash.bashrc /etc/bash.bashrc

# Nettoyage du /etc/skel (pour les utilisateurs futurs)
rm -f /etc/skel/.profile
rm -f /etc/skel/.bashrc

# Nettoyage du /root
rm -f /root/.bashrc
rm -f /root/.profile

# Nettoyage de "homedir"
for USER in `ls /home`
do
	rm -f /home/$USER/.bashrc
	rm -f /home/$USER/.profile
done
